name: Build and push service/interactive to Docker Hub

on:
  push:
    paths:
      - "services/interactive/**"
      - ".github/workflows/**"
    branches: ["main", "dev"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_HUB: anderslaunerbaek
  CONTAINER_NAME: anbae-big-data-course
  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./services/interactive/
          push: false
          tags: ${{ env.DOCKER_HUB }}/${{ env.CONTAINER_NAME }}:${{ github.ref }}