name: Build and push - service/kafka-connect

on:
  push:
    paths:
      - "services/kafka-connect/**"
      - ".github/workflows/**"
    branches: ["main", "dev"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  DOCKERHUB_USERNAME: jakobhviid
  IMAGE_NAME: cp-server-connect-base
  CP_VERSION: 7.3.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:services/kafka-connect/"
          build-args: "CP_VERSION=${{ env.CP_VERSION }}"
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}-${{ env.CP_VERSION }}:latest